preplist/prep/accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
from django.contrib.auth import login, logout
from accounts.views import (
    AvaliablityCreate,
    AvaliablityConfirm,
    AvaliablityDelete,
    available,
    old_post,
    )
app_name ='accounts'

urlpatterns = [
    path('accounts/signup/', views.signup_view,name="signup"),
    path('accounts/old_post/', views.old_post,name="old_post"),
    path('login/', views.login_view,name="login"),
    path('logout/', views.logout_view,name="logout"),
    path('accounts/available_filter/', views.available,name="available_filter"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/',views.profile,name="profile"),
    path('accounts/edit_profile/',views.edit_profile,name="edit_profile"),
    path('accounts/avaliablity_create/',AvaliablityCreate.as_view(), name='avaliablity_create'),
    path('accounts/avaliablity_confirm/',AvaliablityConfirm.as_view(), name='avaliablity_confirm'),
    path('<int:id>/accounts/avaliablity_delete/',AvaliablityDelete.as_view(), name='avaliablity_delete'),
]

preplist/prep/cal/urls.py
from django.urls import path, include
from cal.views import (
    ScheduleFromView,
)

app_name ='cal'

urlpatterns = [
    path('cal/schedule/',ScheduleFromView.as_view(),name='schedule')

]

preplist/prep/items/urls.py
from django.urls import path

from items.views import ProductList, OrderFormView, ThanksPage

app_name = 'items'

urlpatterns = [
    path('product/',ProductList.as_view(), name='product'),
    path('order/',OrderFormView.as_view(), name='order'),
    path('thanks/',ThanksPage.as_view(), name='thanks'),
]

preplist/prep/prep/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from prep.views import HomPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomPageView.as_view(),name='home'),
    path('',include('items.urls')),
    path('',include('todo.urls')),
    path('',include('accounts.urls')),
    path('',include('cal.urls')),

]

preplist/prep/todo/urls.py
from django.urls import path
from . import views
from todo.views import (
    PrepCreate,
    PrepUpdate,
    PrepDelete,
    PrepWorkDetail,
    dailyprep,
)

app_name = 'todo'

urlpatterns = [
    path('prepcreate/',PrepCreate.as_view(), name='prepcreate'),
    path('<int:id>/prepupdate/',PrepUpdate.as_view(), name='prepupdate'),
    path('<int:id>/prepdelete/',PrepDelete.as_view(), name='prepdelete'),
    path('<int:id>/',PrepWorkDetail.as_view(), name='prepwork-detail'),
    path('dailyprep/', views.dailyprep,name='dailyprep'),

]

preplist/prep/items/models.py
from django.db import models


class Product(models.Model):
    product_name = models.CharField(max_length=100)
    par_amount = models.PositiveIntegerField()
    order_amount = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10000, decimal_places=2)
    def __str__(self):
        return self.product_name

preplist/prep/items/forms.py
from django.forms import ModelForm
from items.models import Product

class OrderForm(ModelForm):
    class Meta:
        model = Product
        fields = ['product_name',
                  'order_amount',
                  'par_amount',
                  'price',
        ]

preplist/prep/items/views.py
from django.shortcuts import render, redirect
from .models import Product
from .forms import OrderForm
from django.views.generic import DetailView, ListView
from django.views.generic.edit import FormView
from django.views.generic.base import TemplateView

class ProductList(ListView):
    model = Product
    template_name = 'items/product_list.html'


class OrderFormView(FormView):
    form_class = OrderForm
    template_name = 'items/order_form.html'
    success_url = '/thanks/'

    def form_valid(self,form):
        print(self.request.POST['product_name'])
        return super(OrderFormView,self).form_valid(form)

class ThanksPage(TemplateView):
    template_name = "items/thanks.html"

# def OrderFormView(request):
#     form = OrderForm(request.POST or None)
#     if form.is_valid():
#         form.save()
#         form = OrderForm()
#
#     context = {
#         'form':form
#     }
#     return render(request,'items/order_form.html', context)

preplist/prep/templates/items/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>
      {% block title_block %}
        Base
      {% endblock %}
    </title>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
     <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <!--<li class="nav-item">
         <a class="nav-link" href="{% url 'items:order' %}" style="color:white">Add Product</a>
       </li>
       <li class="nav-item">
         <a class="nav-link" href="{% url 'items:product' %}"style="color:white">Products & Par Amounts</a>
       </li>
       <li class="nav-item">
         <a class="nav-link" href="{% url 'todo:dailyprep' %}"style="color:white">Prep List</a>
       </li>-->
       {% if user.is_authenticated %}
       <!--<li class="nav-item">
         <a class="nav-link" href="{% url 'todo:prepcreate' %}"style="color:white">Prep list maker</a>
       </li>-->
       <li class="nav-item nav">
         <a class="nav-link" href="{% url 'accounts:logout' %}" style="color:white">Logout</a>
       </li>
       <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:avaliablity_create' %}" style="color:white">Needed Time Off</a>
       </li>
       <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:available_filter' %}" style="color:white">Time Requested Off</a>
       </li>
       <li class="nav-item">
         <a class="nav-link" href="{% url 'accounts:profile' %}" style="color:white"> Home</a>
       </li>
       <li class="nav-item">
         <a class="nav-link" href="{% url 'accounts:old_post' %}" style="color:white">~worm hole~</a>
       </li>
       {% else %}
       <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:signup' %}" style="color:white">Sign Up</a>
       </li>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}" style="color:white">Login</a>
       </li>
       {% endif %}
     </ul>
   </div>
    </nav>

  </head>
  <body>
    <div class="container text-center">
      {% block content %}

      {% endblock %}
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

preplist/prep/templates/items/home.html
{% extends 'items/base.html' %}
{% block title_block %}
  Home
{% endblock %}

<div class="container">
  {% block content %}
  {% if user.is_authenticated %}
    <h1>Hi {{ user|capfirst }}!</h1>
  {% else %}
    <p>You are not logged in</p>
  {% endif %}
  {% endblock %}
</div>

preplist/prep/templates/items/order_form.html
{% extends 'items/base.html' %}
{% block title_block %}
  Add Product
{% endblock %}


{% block content %}
<div class="jumbotron">
    <h1 class="display-4"> Add Product to order guide.</h1>
    <hr class="my-4">
    <form method="POST">{% csrf_token %}
      {{form.as_p}}
      <input class="btn btn-primary btn-lg"type="submit" value="Submit Order">
    </form>
</div>
{% endblock %}

preplist/prep/templates/items/product_list.html
{% extends 'items/base.html' %}
{% block title_block %}
  Product
{% endblock %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Total amount per week</h1>
  <br>
<div class="content-container">
  <ul class="list-group">
    {% for product in object_list %}
      <li class="list-group-item">{{ product.product_name }} - weekly par amount <span class="">{{ product.par_amount }}</span></li>
      <br>
      <form  method="POST">
        <input type="number" name="" value="">
      </form>
    {% endfor %}
  </ul>
  <input class="btn btn-primary btn-lg"type="submit" value="Submit Order">{% csrf_token %}
</div>
{% endblock %}

preplist/prep/templates/items/thanks.html
{% extends 'items/base.html' %}
{% block title_block %}
  Mission Accomplished
{% endblock %}

{% block content %}
<h1>Mission Accomplished!! You have successfully added a product.</h1>
{% endblock %}

preplist/prep/templates/items/thanos.html
{% extends 'items/base.html' %}
{% block title_block %}
  Item Deleted
{% endblock %}

{% block content %}
<h1>You Thanoes'ed that item.</h1>
{% endblock %}